# -*- coding: utf-8 -*-
"""01)-04 불용어(stopword).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TxSXsZMI-VCm7hgpQG8hD-Rzzb5GohMU
"""

!pip install konlpy

import nltk
nltk.download('stopwords')

import nltk
nltk.download('punkt')

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from konlpy.tag import Okt

## nltk에서 불용어를 확인해본다.
stop_words_list = stopwords.words('english')
print('영어의 불용어 개수:', len(stop_words_list))
stop_words_list[:10]

### 2. nltk를 통해 불용어 제거

example = "Family is not important thing. It's everything."
stop_words = set(stopwords.words('english'))

word_tokens = word_tokenize(example)

result = []
for word in word_tokens:
  if word not in stop_words:
    result.append(word)

print('불용어 제거 전:', word_tokens)
print('불용어 제거 후:', result)

### 3. 한국어 불용어 제거

from konlpy.tag import Okt
okt = Okt()

example = '꼼장어는 아무렇게나 구우면 안돼. 고기라고 다 같은 게 아니거든. 예건데 꼼장어는 구울 때 기억해야 할 것이 있지.'
stop_words_korean = '는 아무렇게나 구우면 안돼 다 거든'

stop_words_korean = set(stop_words_korean.split(' '))
stop_words_korean

## okt를 활용해서 형태소 분석 및 토큰화 작업
word_tokens1 = okt.morphs(example)

result = [word for word in word_tokens1 if not word in stop_words_korean]

print('불용어 제거 전:', word_tokens1)
print('불용어 제거 후:', result)

# end of files