# -*- coding: utf-8 -*-
"""01)-02_정제 및 정규화.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17lDhuqO8570Z09jzXYleCDmy4ihzOGWs

에디가 책을 읽었다

자립형태소 :: 에디, 책 (noun)

의존형태소 :: 가, 을(josa) 읽다.

I was sitting in my 11st grade world world history when ms. taylor announced a ne project...

여러분과 제가 만난지 벌써 2달이 되어갑니다. 너무 아쉽고 감사합니다. 마지막까지 화이팅 하시죠.

##### * 정제(cleaning) : 갖고 있는 corpus(말뭉치)로부터 노이즈 데이터를 제거

##### * 정규화(normalization) : 표현 방법이 다른 단어들을 통합시켜 같은 형태로 변환

1) 규칙에 기반한 표기로 단어들을 통합

2) 대문자를 소문자로 전부 변환 후 통합

3) 불필요 단어들을 제거 - 

    (1) 등장 빈도가 적은 단어

    (2) 길이가 짧은 단어 :: 영어권 - stopword(불용어)
"""

### 정규표현식 re :: Reqular Expression

import re
text = 'I was wondering if anyone out there could enlight me on this car'
## 길이가 1~2인 단어들을 제거 by using RE
shortword = re.compile(r'\\W*\\b\\w{1,2}\\b')
shortword.sub('', text)

# end of files