# -*- coding: utf-8 -*-
"""13)PDF_python_예제.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SWmzY5th3kC9xnghjEfteHUKVXKrd6T9
"""

!pip install PyPDF2

## PyPDF2모듈을 사용하여 Python으로 PDF 읽기

from PyPDF2 import PdfFileReader
temp = open('/content/drive/MyDrive/Colab Notebooks/98_crawling_scraping/woori.pdf', 'rb')
PDF_read = PdfFileReader(temp)
first_page = PDF_read.getPage(0)
print(first_page.extractText())

!pip install PDFplumber

## pdfplumber모듈을 사용하여 Python으로 PDF 읽기

import pdfplumber
with pdfplumber.open('/content/drive/MyDrive/Colab Notebooks/98_crawling_scraping/woori.pdf') as temp:
  first_page = temp.pages[0]
  print(first_page.extract_text())

!pip install pdfminer.six

from pdfminer.high_level import extract_text
PDF_read = extract_text('/content/drive/MyDrive/Colab Notebooks/98_crawling_scraping/woori.pdf')
print(PDF_read)

